language: cpp
sudo: false

cache:
  apt: true
  directories:
    - $HOME/.cache/cmake
    - $HOME/.cache/boost

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
        #- llvm-toolchain-precise-3.5
    packages:
      - libvtk5-dev
      - libopenmpi-dev
      - g++-4.9
      #- clang-3.5
      #- g++-5
      #- g++-6

env:
  global:
    - CMAKE_ROOT: $HOME/.cache/cmake
    - BOOST_ROOT: $HOME/.cache/boost
    - BOOST_VER: 105800 # careful: hard coded below
    - DODO_ROOT: $TRAVIS_BUILD_DIR
  matrix:
    - COMPILER=gcc
    #- COMPILER=clang
    #- COMPILER=gcc5
    #- COMPILER=gcc6

before_install:
  - mkdir -p $HOME/build
  - export CMAKE_FLAGS=""
  - if [ "$COMPILER" == "gcc" ]; then
        echo "Using g++-4.9 ...";
        export CXX=g++-4.9;
        export CC=gcc-4.9;
    elif [ "$COMPILER" == "gcc5" ]; then
        echo "Using g++-5 ...";
        export CXX=g++-5;
        export CC=gcc-5;
    elif [ "$COMPILER" == "gcc6" ]; then
        echo "Using g++-6 ...";
        export CXX=g++-6;
        export CC=gcc-6;
    elif [ "$COMPILER" == "clang" ]; then
        echo "Using clang++-3.5 ...";
        export CXX=clang++-3.5;
        export CC=clang-3.5;
    fi
  - echo "$CMAKE_FLAGS"
  - echo "$CXX $CC"
  - $CXX --version
  - $CC --version

install:
  #############################################################################
  # CMAKE                                                                     #
  #############################################################################
  - export PATH=$CMAKE_ROOT/bin:$PATH
  - CMAKE_33_FOUND=$(cmake --version | grep " 3\.3\." >/dev/null && { echo 0; } || { echo 1; })
  - if [ $CMAKE_33_FOUND -ne 0 ]; then
      mkdir -p $CMAKE_ROOT &&
      cd $CMAKE_ROOT &&
      travis_retry wget --no-check-certificate http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz &&
      tar -xzf cmake-3.3.2-Linux-x86_64.tar.gz --overwrite &&
      mv -f cmake-3.3.2-Linux-x86_64/* . &&
      rm -rf cmake-3.3.2-Linux-x86_64.tar.gz cmake-3.3.2-Linux-x86_64 &&
      cd -;
    fi
  - cmake --version
  #############################################################################
  # BOOST                                                                     #
  #############################################################################
  - export CMAKE_PREFIX_PATH=$BOOST_ROOT:$CMAKE_PREFIX_PATH
  - echo -e "#include <boost/version.hpp>\n#include <iostream>\nint main() { std::cout << BOOST_VERSION << std::endl; return 0; }"
        | $CXX -I$BOOST_ROOT/include -x c++ - >/dev/null || { echo 0; }
  - ls $BOOST_ROOT
  - BOOST_FOUND=$([ $(./a.out) -eq $BOOST_VER ] && { echo 0; } || { echo 1; })
  - if [ $BOOST_FOUND -ne 0 ]; then
      mkdir -p $ BOOST_ROOT &&
      cd $BOOST_ROOT &&
      travis_retry wget --no-check-certificate -O boost.tar.bz2 http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.bz2/download &&
      tar -xjf boost.tar.bz2 &&
      cd boost_1_58_0 &&
      echo "using gcc "":"" 4.9 "":"" /usr/bin/g++-4.9 ; " >> tools/build/src/user-config.jam &&
      cat tools/build/src/user-config.jam &&
      ./bootstrap.sh toolset=gcc --with-libraries=filesystem,program_options --prefix=$BOOST_ROOT &&
      ./b2 -j2 &&
      ./b2 install &&
      rm -rf boost.tar.bz2 boost_1_58_0 &&
      cd $HOME;
    fi
      #echo "using gcc "":"" 6 "":"" /usr/bin/g++-6 ; " >> tools/build/src/user-config.jam &&
      #echo "using clang "":"" 3.5 "":"" /usr/bin/clang++-3.5 ; " >> tools/build/src/user-config.jam &&
      #echo "using gcc "":"" 5 "":"" /usr/bin/g++-5 ; " >> tools/build/src/user-config.jam &&

script:
  - cd $HOME/build
  - cmake $CMAKE_FLAGS $DODO_ROOT/
  - make
